### ISSUE TITLE
A little help if you have the time to respond

### ISSUE THREAD

**Issue by nemesis911** [lohanjs/easyequities#2]
Ive been trying to get this to run on my Mac, Ive got all the requirements you listed but i am having issues, Ive looked up some help, i am a bit stumped. I ran a VM with Debian on it and got all the requirements you listed, i still couldn't get it to work. Set all paths etc. I keep on hitting a dead end.

Could you suggest an OS i should use, and what versions of the requirements i should download and install. Not asking for a step by step guide, could you just point me in the right direction please, ill try and figure it out as i go along.

Thanks in advance.

**Comment by lohanjs** [comment]
To be quite honest I'm not sure what the issue might be. For what it's worth, I primarily use Windows and have tested it on it, but I don't think the OS plays a part here. If you could maybe be more specific about the errors you're getting, that would be helpful.
